<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HomeGrown Monthly Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; }
        h1, h2 { color: #E9896A; }
        .section { margin-bottom: 30px; }
        .card { background: #FFF8F4; padding: 10px 15px; margin-bottom: 10px; border-radius: 6px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #E9896A; color: white; }
    </style>
</head>
<body>

<h1>HomeGrown Monthly Report</h1>
<p>Date: {{ \Carbon\Carbon::create(now()->year, $month, 1)->format('F Y') }}</p>

<!-- Platform Summary -->
<div class="section">
    <h2>Platform Summary</h2>
    <div class="card">Total Customers: {{ $overview['total_customers'] }}</div>
    <div class="card">Total Artisans: {{ $overview['total_artisans'] }}</div>
    <div class="card">Total Exhibition Owners: {{ $overview['total_exhibition_owners'] }}</div>
    <div class="card">Products Last Month: {{ $overview['products_last_month'] }}</div>
    <div class="card">Exhibitions Last Month: {{ $overview['exhibitions_last_month'] }}</div>
    <div class="card">Orders Last Month: {{ $overview['orders_last_month'] }}</div>
    <div class="card">New Users Last Month: {{ $overview['new_users_last_month'] }}</div>
</div>

<!-- Monthly Growth -->
<div class="section">
    <h2>Monthly Growth</h2>
    <table>
        <tr>
            <th>Month</th>
            @foreach($growth['labels'] as $label)
            <th>{{ $label }}</th>
            @endforeach
        </tr>
        <tr>
            <td>Users</td>
            @foreach($growth['users'] as $val)
            <td>{{ $val }}</td>
            @endforeach
        </tr>
        <tr>
            <td>Products</td>
            @foreach($growth['products'] as $val)
            <td>{{ $val }}</td>
            @endforeach
        </tr>
        <tr>
            <td>Orders</td>
            @foreach($growth['orders'] as $val)
            <td>{{ $val }}</td>
            @endforeach
        </tr>
        <tr>
            <td>Exhibitions</td>
            @foreach($growth['exhibitions'] as $val)
            <td>{{ $val }}</td>
            @endforeach
        </tr>
    </table>
</div>

<!-- Top Rankings -->
<div class="section">
    <h2>Top Rankings</h2>

    <h3>Top Products</h3>
    <table>
        <tr>
            <th>#</th><th>Name</th><th>Artisan</th><th>Sales</th><th>Likes</th>
        </tr>
        @foreach($topRankings['top_products'] as $i => $product)
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $product['name'] }}</td>
            <td>{{ $product['subtitle'] }}</td>
            <td>{{ $product['sales'] }}</td>
            <td>{{ $product['likes'] }}</td>
        </tr>
        @endforeach
    </table>

    <h3>Top Artisans</h3>
    <table>
        <tr>
            <th>#</th><th>Name</th><th>Followers</th><th>Rating</th><th>Products</th><th>Sales</th>
        </tr>
        @foreach($topRankings['top_artisans'] as $i => $artisan)
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $artisan['name'] }}</td>
            <td>{{ $artisan['followers'] }}</td>
            <td>{{ $artisan['rating'] }}</td>
            <td>{{ $artisan['products'] }}</td>
            <td>{{ $artisan['sales'] }}</td>
        </tr>
        @endforeach
    </table>

    <h3>Top Exhibitions</h3>
    <table>
        <tr>
            <th>#</th><th>Owner</th><th>Title</th><th>Interested Users</th>
        </tr>
        @foreach($topRankings['top_exhibitions'] as $i => $exhibition)
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $exhibition['subtitle'] }}</td>
            <td>{{ $exhibition['name'] }}</td>
            <td>{{ $exhibition['interested_users'] }}</td>
        </tr>
        @endforeach
    </table>
</div>

<div class="section">
    <p>Generated by HomeGrown Admin Dashboard</p>
</div>

</body>
</html>